// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA8wIC9HbSizFmVqbIbpk4TatdfeZpg3o',
    appId: '1:295019090453:web:ea92c34123aa337a32f41c',
    messagingSenderId: '295019090453',
    projectId: 'bookabuku-b5802',
    authDomain: 'bookabuku-b5802.firebaseapp.com',
    storageBucket: 'bookabuku-b5802.appspot.com',
    measurementId: 'G-LDL9XX8706',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfb_2p6SHkEg_hSKQuJuhjR0fprW_l9Yg',
    appId: '1:295019090453:android:5947c6df37b538e232f41c',
    messagingSenderId: '295019090453',
    projectId: 'bookabuku-b5802',
    storageBucket: 'bookabuku-b5802.appspot.com',
  );
}
